In [19]:
from tensorflow.keras.preprocessing.text import one_hot

Sentences

In [20]:
sentence=[
  'the glass of milk',
  'the glass of juice',
  'the cup of tea',
  'I am a good boy',
  'I am a good developer',
  'understand the meaning of words',
  'your videos are good',
]

In [21]:
sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

Define the Vacabulary Size

In [22]:
voc_size=10000

One Hot Representation

In [23]:
one_hot_rep=[one_hot(words,voc_size) for words in sentence]
one_hot_rep

[[934, 2825, 8589, 2020],
 [934, 2825, 8589, 3666],
 [934, 7464, 8589, 1715],
 [6615, 6212, 3855, 7306, 6955],
 [6615, 6212, 3855, 7306, 162],
 [3932, 934, 2070, 8589, 8006],
 [9045, 8852, 3622, 7306]]

Word Embedding Representation

In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
sentence_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0    0  934 2825 8589 2020]
 [   0    0    0    0  934 2825 8589 3666]
 [   0    0    0    0  934 7464 8589 1715]
 [   0    0    0 6615 6212 3855 7306 6955]
 [   0    0    0 6615 6212 3855 7306  162]
 [   0    0    0 3932  934 2070 8589 8006]
 [   0    0    0    0 9045 8852 3622 7306]]


Feature Representation

In [26]:
dimension=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dimension,input_shape=(sentence_length,)))
model.compile('adam','mse')

c:\Users\ROHIT GUPTA\miniconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [30]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 644ms/step


array([[[ 0.00769292,  0.03160942,  0.02133754,  0.03283555,
         -0.01485063,  0.04876387, -0.02817036, -0.03945745,
         -0.00506509,  0.04955758],
        [ 0.00769292,  0.03160942,  0.02133754,  0.03283555,
         -0.01485063,  0.04876387, -0.02817036, -0.03945745,
         -0.00506509,  0.04955758],
        [ 0.00769292,  0.03160942,  0.02133754,  0.03283555,
         -0.01485063,  0.04876387, -0.02817036, -0.03945745,
         -0.00506509,  0.04955758],
        [ 0.00769292,  0.03160942,  0.02133754,  0.03283555,
         -0.01485063,  0.04876387, -0.02817036, -0.03945745,
         -0.00506509,  0.04955758],
        [-0.02203752,  0.02521219, -0.00471592, -0.0012219 ,
          0.03750071,  0.01875887,  0.01789   ,  0.0104441 ,
          0.02185692, -0.00929119],
        [-0.00504459,  0.01778981, -0.03873117,  0.04973662,
         -0.01152152, -0.03589512,  0.04437076, -0.03377511,
         -0.02144457,  0.02665052],
        [-0.04553209, -0.03887141,  0.01628978,  0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0,  934, 2825, 8589, 2020])

In [38]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


array([[ 0.00769292,  0.03160942,  0.02133754,  0.03283555, -0.01485063,
         0.04876387, -0.02817036, -0.03945745, -0.00506509,  0.04955758],
       [ 0.00769292,  0.03160942,  0.02133754,  0.03283555, -0.01485063,
         0.04876387, -0.02817036, -0.03945745, -0.00506509,  0.04955758],
       [ 0.00769292,  0.03160942,  0.02133754,  0.03283555, -0.01485063,
         0.04876387, -0.02817036, -0.03945745, -0.00506509,  0.04955758],
       [ 0.00769292,  0.03160942,  0.02133754,  0.03283555, -0.01485063,
         0.04876387, -0.02817036, -0.03945745, -0.00506509,  0.04955758],
       [-0.02203752,  0.02521219, -0.00471592, -0.0012219 ,  0.03750071,
         0.01875887,  0.01789   ,  0.0104441 ,  0.02185692, -0.00929119],
       [-0.00504459,  0.01778981, -0.03873117,  0.04973662, -0.01152152,
        -0.03589512,  0.04437076, -0.03377511, -0.02144457,  0.02665052],
       [-0.04553209, -0.03887141,  0.01628978,  0.02701498, -0.04374569,
         0.03874471,  0.02818788,  0.04349605